export const ACTION_CONST = {
    REQUEST_SUBMIT: 'REQUEST_SUBMIT',
    REQUEST_DONE: 'REQUEST_DONE',
    ALERT_SUCCESS: 'ALERT_SUCCESS',
    ALERT_FAILS: 'ALERT_FAILS',
    ALERT_WARNING: 'ALERT_WARNING',
    ALERT_CLEAR: 'ALERT_CLEAR',
    ALERT_LINK: 'ALERT_LINK',
    ALERT_LINK_CLEAR: 'ALERT_LINK_CLEAR',
    SUBMIT_GET_WALLETS: 'SUBMIT_GET_WALLETS',
    GET_WALLETS_SUCCESS: 'GET_WALLETS_SUCCESS',
    SUBMIT_WALLET_FORM: 'SUBMIT_WALLET_FORM',
    SUBMIT_WALLET_SUCCESS: 'SUBMIT_WALLET_SUCCESS',
    DELETE_WALLET: 'DELETE_WALLET',
    DELETE_WALLET_SUCCESS: 'DELETE_WALLET_SUCCESS'
}